version: "3.8"

services:
  ai:
    container_name: ai
    build: .
    command: python main.py --no-gpus
    volumes:
      - .:/code
    ports:
      - "5500:5500"
      - "80:80"

    networks:
      - ai-net

  rabbitmq:
    image: rabbitmq:3.6.6
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  redis:
    image: redis
    ports:
    - "6379:6379"


networks:
  ai-net:
    driver: bridge
