version: "3.8"

services:
  ai:
    container_name: ai
    build: .
    command: python main.py --no-gpus
    volumes:
      - .:/code
    ports:
      - "5500:5500"
      - "80:80"

    networks:
      - ai-net

networks:
  ai-net:
    driver: bridge
