name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        TAG: latest
      run: docker build . --file Dockerfile --tag docker.tommcn.mcnamer.ca/crowdeye-ai:$TAG && docker push docker.tommcn.mcnamer.ca/crowdeye-ai:$TAG
