name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v2.2.2
      name: Build and push the Docker image
      with:
        push: true
        tags: latest
